# Generated by Django 4.2 on 2025-11-28 07:16

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultationrequest',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='consultation_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('kitchen', 'Kitchen Remodeling'), ('bathroom', 'Bathroom Remodeling'), ('garage', 'Garage Remodeling'), ('fullhouse', 'Full House Remodeling'), ('adu', 'ADU'), ('newconstruction', 'New Construction')], max_length=53),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
