# Generated by Django 4.2 on 2025-11-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_submitted_at_consultationrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsultationRequest',
            new_name='LeadModel',
        ),
    ]
