# Generated by Django 4.2.16 on 2025-12-11 02:47

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_consultationrequest_leadmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadmodel',
            options={'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterField(
            model_name='leadmodel',
            name='consultation_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('kitchen', 'Kitchen Remodeling'), ('bathroom', 'Bathroom Remodeling'), ('garage', 'Garage Remodeling'), ('fullhouse', 'Full House Remodeling'), ('newconstruction', 'New Construction'), ('adu', 'ADU')], max_length=53),
        ),
        migrations.AlterField(
            model_name='leadmodel',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
