# Generated by Django 4.2.16 on 2025-12-21 00:22

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_project_projectconstructionimage_projectbeforeimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectafterimage',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='projectbeforeimage',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='projectconstructionimage',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='projectafterimage',
            name='image_wm',
            field=models.ImageField(blank=True, editable=False, upload_to=home.models.project_upload_to),
        ),
        migrations.AddField(
            model_name='projectbeforeimage',
            name='image_wm',
            field=models.ImageField(blank=True, editable=False, upload_to=home.models.project_upload_to),
        ),
        migrations.AddField(
            model_name='projectconstructionimage',
            name='image_wm',
            field=models.ImageField(blank=True, editable=False, upload_to=home.models.project_upload_to),
        ),
    ]
