# Generated by Django 4.2.16 on 2025-12-21 02:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_projecttag_project_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='project_name',
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail_title',
            field=models.CharField(default=django.utils.timezone.now, help_text='Short title shown on project thumbnail', max_length=120),
            preserve_default=False,
        ),
    ]
