# Generated by Django 4.2.16 on 2025-12-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_project_options_project_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='highlights',
            field=models.TextField(blank=True, help_text='Enter one highlight per line (e.g. COMPLETED 2022 MAY)'),
        ),
    ]
